steps:
  # Build Docker image
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "us-central1-docker.pkg.dev/$PROJECT_ID/$PROJECT_ID/app:$COMMIT_SHA",
        ".",
      ]

  # Deploy to Cloud Run with environment variables from Secret Manager
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "run"
      - "deploy"
      - "$PROJECT_ID"
      - "--image=us-central1-docker.pkg.dev/$PROJECT_ID/$PROJECT_ID/app:$COMMIT_SHA"
      - "--platform=managed"
      - "--region=us-central1"
      - "--allow-unauthenticated"
      - "--port=8080"
      - "--memory=512Mi"
      - "--cpu=1"
      - "--max-instances=10"
      - "--set-env-vars=NODE_ENV=production"
      - "--set-secrets=BOT_TOKEN=bot-token:latest,DATABASE_URL=database-url:latest,WHISPER_API_KEY=whisper-api-key:latest,SELF_BACKEND_ENDPOINT=self-backend-endpoint:latest,OPENAI_API_KEY=openai-api-key:latest,ASSISTANT_ID=assistant-id:latest,HMAC_SECRET_KEY=hmac-secret-key:latest,HASH_SALT=hash-salt:latest"

# Push image to Artifact Registry
images:
  - "us-central1-docker.pkg.dev/$PROJECT_ID/$PROJECT_ID/app:$COMMIT_SHA"

# Build configuration
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: "E2_HIGHCPU_8"

timeout: "1200s"
