steps:
  # Install Bun
  - name: "ubuntu"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        curl -fsSL https://bun.sh/install | bash
        export PATH="$PATH:/root/.bun/bin"
        echo "Bun installed successfully"
        bun --version
    id: "install-bun"

  # Install dependencies with Bun
  - name: "ubuntu"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        export PATH="$PATH:/root/.bun/bin"
        bun install
    id: "install-deps"
    waitFor: ["install-bun"]

  # Build TypeScript with Bun
  - name: "ubuntu"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        export PATH="$PATH:/root/.bun/bin"
        bun run build
    id: "build"
    waitFor: ["install-deps"]

  # Deploy to App Engine
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "gcloud"
    args: ["app", "deploy", "--quiet"]
    id: "deploy"
    waitFor: ["build"]

# Timeout for the entire build (20 minutes)
timeout: "1200s"

# Specify machine type for faster builds
options:
  machineType: "E2_HIGHCPU_8"
  logging: CLOUD_LOGGING_ONLY
