name: Deploy to GCP VM

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: SSH Deploy to GCP
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Add SSH Key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.GCP_SSH_KEY }}

      - name: Deploy to GCP
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.GCP_USER }}@${{ secrets.GCP_VM_IP }} << 'EOF'
            set -e

            # Install updates and essential tools
            sudo apt update && sudo apt install -y git curl unzip

            # Install Node.js (LTS)
            curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
            sudo apt install -y nodejs

            # Install Bun if missing
            if ! command -v bun &> /dev/null; then
              curl -fsSL https://bun.sh/install | bash
              echo 'export PATH="$HOME/.bun/bin:$PATH"' >> ~/.bashrc
              source ~/.bashrc
            fi

            export PATH="$HOME/.bun/bin:$PATH"
            cd $HOME

            # Clone the repository if it doesn't exist
            if [ ! -d "deepgov-bot" ]; then
              git clone https://github.com/gainforest/deepgov-bot.git
            fi
            cd deepgov-bot
            git reset --hard
            git pull

            # Set environment variables from secrets
            echo "${{ secrets.ENV_FILE }}" > .env.local

            # Install dependencies and start the bot
            bun install
            bun add -g pm2

            pm2 restart deepgov-bot || pm2 start "bun run start" --name deepgov-bot
            pm2 save
          EOF
